### ISSUE TITLE
实现一个 Object.assign polyfill

### ISSUE THREAD

**Issue by egoist** [hayeah/js-gym#22]
```js
function objectAssign() {
  // ... your code
}

objectAssign({foo: 0}, {bar: 1})
//=> {foo: 0, bar: 1}

// 多个对象
objectAssign({foo: 0}, {bar: 1}, {baz: 2})
//=> {foo: 0, bar: 1, baz: 2}

// 覆盖已存在的 key
objectAssign({foo: 0}, {foo: 1}, {foo: 2})
//=> {foo: 2}

// 忽略 null 和 undefined
objectAssign({foo: 0}, null, {bar: 1}, undefined)
//=> {foo: 0, bar: 1}
```

---

参考:

- https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by hayeah** [comment]
merged

**Comment by egoist** [comment]
[studiosoriginals-bugg-buddies-3oz8xJcPzeRutjp2BW](https://camo.githubusercontent.com/22d987bb31227ac9a823a6245973936b1b53614d/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a38784a63507a655275746a703242572f67697068792e676966>)

**Comment by egoist** [comment]
![studiosoriginals-bugg-buddies-3oz8xJcPzeRutjp2BW](https://camo.githubusercontent.com/22d987bb31227ac9a823a6245973936b1b53614d/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f7a38784a63507a655275746a703242572f67697068792e676966>)
